url: "https://www.passulo.com" # for robots, sitemap
baseurl: ""
name: "Passulo"
destination: docs/
appstore: https://apps.apple.com/app/passulo/id1610341734

plugins:
  - jekyll-sitemap
  - jekyll-polyglot
#  - jekyll-feed # RSS feed for posts

languages: [ "en", "de" ]
default_lang: "de"
exclude_from_localization: [ "images", "css", "favicon.ico", "apple-touch-icon.png", "docs" ]
parallel_localization: true
lang_from_path: true
highlighter: rouge

collections:
  - changelog
  - faq
  - explainers

menu:
  home:
    de: Home
    en: Home
  examples:
    de: Beispiele
    en: Examples
  architecture:
    de: Architektur
    en: Architecture
  spec:
    de: Spezifikation
    en: Specification
  faq:
    de: Fragen & Antworten
    en: FAQ
  download:
    de: Download
    en: Download
  software:
    de: Software
    en: Software
#  language:
#    de: Deutsch
#    en: English

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - website.iml
  - .gitignore
  - .idea
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
