name: Build & Deploy via SFTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Build site
        uses: lemonarc/jekyll-action@1.0.0

      - name: Deploy File
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SERVER_USERNAME }}'
          server: '${{ secrets.SERVER_IP }}'
          port: '${{ secrets.SERVER_PORT }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './_site/*'
          remote_path: '/home/webnhdsfg/html/oma'
          args: '-o ConnectTimeout=5'